--- # Upload the Shell Script to Remote Host and Run it.
-  hosts: sonar
   remote_user: centos
   become: yes
   become_method: sudo
   connection: ssh
   gather_facts: yes    
   vars:
      java_packages:
        - java-1.8.0-openjdk
   roles:
     - ansible-role-java
     - ansible-role-sonarqube
